import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "./styles/globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "./providers/ThemeProvider"
import { ClerkProvider } from "@clerk/nextjs"
import { ModalProvider } from "./providers/ModalProvider"
import ToastProvider from "./providers/ToastProvider"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ToastProvider />
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
